kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: roboshop-efs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0a0c153b5f0d9f697
  directoryPerms: "700"
  basePath: "/roboshop" # optional


  # usually ga for each project ki okati create chestam