
apiVersion: v1
kind: Pod
metadata:
  name: error-test
  namespace: roboshop
spec:
  containers:
  - name: nginx
    image: ngindfdfadsfsaf # see notes
  # - name: almalinux
  #   image: almalinux:9  # run chese cmd emi ledhu so we will get error 