apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  # these are replica set resource ki vunde labels
  labels:
    purpose: rs-demo
    project: roboshop
spec:
  replicas: 2
  selector:
    # these labels are used to select pods, which pod ni select chesi, duplicat pod creaet cheyali 
    matchLabels:
      purpose: rs-demo
      project: roboshop

  # pod definition
  template:
    metadata:
      labels:
        purpose: rs-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx
        # image: nginx:trixie-perl  # new image 

    

# so selectoir lo vunnna labels tisukoni velli aa pod ki match avuthunayo aa pod dhaggara template lo vunde 
#configuraton tho new pod create chei if load is increased ani means


       


